config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  
  get 'home' => 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'


  devise_for :users, path: '',
    path_names:  {},
    controllers: {
      registrations: 'users/registrations',
      sessions:      'users/sessions',
      passwords:     'users/passwords'
    }

   

  resources :books
  resources :rentals

  get '*any', via: :all, to: 'errors#not_found'
end

app/models/book.rb
class Book < ActiveRecord::Base
  validates_presence_of :title,:year
  validates_numericality_of :year, :only_integer => true
  validates_uniqueness_of :title, :scope => :year
  after_initialize :defaults

  def mark_as_rented
    self.status =  "rented"
    self.save
  end
  
  private
  def defaults
    self.status ||= "available"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(user_params)
    if @book.save
      flash[:notice] = "Book added successfully!"
      redirect_to book_path(@book)
    else
      render 'books/new'
    end
  end

  def index
    @books = Book.all
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice] = "Book deleted successfully!"
      redirect_to books_path
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(user_params)
      flash[:notice] = "Book upated successfully!"
      redirect_to books_path
    else
      render 'books/edit'
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  private

	  def user_params
	    params.require(:book).permit(:title, :author, :year, :genre, :description)
	  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <h2> <%= pluralize(@book.errors.count,"error") %> prevented book from being saved: </h2>
    <p> There were problems with the following fields: </p>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li> <%= "#{msg}" %> </li>
    <% end %>
    </ul>
   <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script>
  $('textarea').froalaEditor();
</script>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/movies/destroy.html.erb</p>

app/views/books/edit.html.erb
<h2>Edit Book</h2>
<%= render 'form' %>

app/views/books/index.html.erb
<h2>Book Listing</h2>
<table>
<tr>
<th>Book</th>
<th>Author</th>
<th>Genre</th>
<th>Description</th>
</tr>

<% @books.each do |book| %>
  <tr>
  <td> <%= link_to book.title, book_path(book) %> </td>
  <td> <%= book.author %> </td>
  <td> <%= book.genre %> </td>
  <td> <%= book.description.html_safe %> </td>
  <td> <%= link_to "Edit", edit_book_path(book) %> </td>
  <td> <%= link_to "Delete", book_path(book), :method => "delete", :confirm => "Are you sure?" %> </td>
  </tr>
<% end %>
</table>
<p>
<%= link_to "Add Book", new_book_path %>
<%= link_to "Rent a Book", new_rental_path %>
<%= link_to "Customers", edit_user_registration_path %>
</p>

app/views/books/new.html.erb
<h2>Create Book</h2>
<%= render 'form' %>



<h2> 책 검색 </h2>
<form id="search">
  Title:<br>
  <input type="text" id="title" name="title" value=""><br>
  <input type="submit" value="Submit">
</form>

<ul class="list-group" id="list"></ul>
<script>
  

  $("#search").submit(function(e) {
    
    var url = "https://apis.daum.net/search/book";
    var title = $(this).find("#title").val() || "코딩클럽";
    console.log(title);
    $.ajax({
          url: url,
          data: {apikey: "eac6131f84cc5fa82ba7bb2612c1607f", 
               q: title, 
               sort: "popular",
               pageno: 1,
               output: "json"
          },
          dataType : "jsonp",
        type : "post",
        jsonp : "callback",

          success: function(data){
            var html = '';
            $.each( data.channel.item, function(i,item){
              console.log( JSON.stringify(item) );

              html += "<li class='list-group-item' data='"+ JSON.stringify(item) +"'>" + item.title + "</li>";
            });
            $("#list").html(html);

            // 새로 렌더한 li tag에 대한 클릭 이벤트 바인딩
            $(".list-group-item").click( function(e){
              e.preventDefault();
              addBookOnList( JSON.parse( $(this).attr('data') ) );
            });

          },error :function(xhr,response){
            console.log("Error code is "+xhr.status+" and the error is "+response);
          }
      });

      e.preventDefault(); // avoid to execute the actual submit of the form.


  });

  
  function addBookOnList(info){
    //console.log(typeof JSON.parse(info)
    document.getElementById('book_title').value = info.title;
    document.getElementById('book_author').value = info.author;
    document.getElementById('book_year').value = info.pub_date;
    document.getElementById('book_genre').value = info.category;
    //document.getElementById('book_description').value = info.description;
    $(".fr-element.fr-view").html(info.description);
    //console.log(info);
  }
</script>

app/views/books/show.html.erb
<h2>Book: <%= @book.title %> </h2>
<ul>
<li>Author: <%= @book.author %> </li>
<li>Release Year: <%= @book.year %> </li>
<li>Genre: <%= @book.genre %> </li>
<li>Description: <%= @book.description.html_safe %> </li>
</ul>
<p><%= link_to "Book Listing", books_path %></p>

app/views/books/update.html.erb
<h1>Movies#update</h1>
<p>Find me in app/views/movies/update.html.erb</p>